### ISSUE TITLE
 Random code problem

### ISSUE THREAD

**Issue by fail572872916** [androidthings/sample-uartloopback#10]
I want to input the content I input in aruino at Log, but there is a garbled problem and how to solve it.
![tim 20181105160538](https://user-images.githubusercontent.com/19763500/47985487-ac3bdd00-e114-11e8-85e1-f1428e19fbac.png)
![tim 20181105160635](https://user-images.githubusercontent.com/19763500/47985585-118fce00-e115-11e8-8e8a-b686d63846db.png)

**Comment by Fleker** [comment]
Can you print out the character codes of each character? My guess, from looking at this, is that you're reading in a ton of characters at a time, more than the sending device is sending. As such, it is going to read in one character and leave the rest as nulls (character code '0').

Keep in mind the data types you're passing back and forth. If your Arduino is sending numbers, you should be looking at the numbers coming back and not the associated characters.

**Comment by fail572872916** [comment]
I have solved this problem.
![tim 20181106114153](https://user-images.githubusercontent.com/19763500/48041685-42294380-e1b9-11e8-81d7-0c5accb26d3f.png)
               Thank you for your project.
