### ISSUE TITLE
Installation failed 

### ISSUE THREAD

**Issue by JeffersonHuang** [androidthings/sample-uartloopback#13]
10/22 12:17:24: Launching 'app' on rockchip rk3399-mid.
Installation did not succeed.
The application could not be installed: INSTALL_FAILED_MISSING_SHARED_LIBRARY
Installation failed due to: 'null'

**Comment by Fleker** [comment]
As far as I know, the Rockchip RK3399 doesn't run Android Things.

**Comment by JankingHuang** [comment]
Thank your

**Comment by JeffersonHuang** [comment]
> As far as I know, the Rockchip RK3399 doesn't run Android Things.

Thank your
